
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export REDISCLOUD_URL=redis://localhost:6379
export AMAZON_ACCESS_KEY=access
export AMAZON_SECRET=secret
export AWS_S3_BUCKET_NAME=com.arttwo50

