
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

export REDISCLOUD_URL=redis://localhost:6379
export AMAZON_ACCESS_KEY=access
export AMAZON_SECRET=secret
export AWS_S3_BUCKET_NAME=com.arttwo50
export AMAZON_HOST=http://com.arttwo50.s3.amazonaws.com
export BONSAI_URL=https://f51fylvt:82zmyzt0d6kniac@alder-4507061.us-east-1.bonsai.io
